/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cute_mug_-_free_3d_model.glb 
Author: PolyCube (https://sketchfab.com/ItsPolyCube)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cute-mug-free-3d-model-c329807e8b354e3883d8e6a1596563ae
Title: Cute Mug - Free 3D model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cute_mug_-_free_3d_model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.479, -0.062, 0.075]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0.042, -0.283, -0.055]} rotation={[-0.124, 0.209, 0.233]} scale={[1.148, 0.857, 1.148]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} position={[-0.2, 0.635, -0.065]} rotation={[-0.096, 0.223, 0.103]} scale={[0.939, 0.864, 0.939]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[-1.41, -0.049, 0.226]} rotation={[-0.124, 0.209, 0.233]} scale={[0.149, 0.448, 0.121]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} position={[-0.395, 0.418, 0.935]} rotation={[-0.124, 0.209, 0.233]} scale={0.09} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.007']} position={[0.146, 0.414, 1.003]} rotation={[-0.124, 0.209, 0.233]} scale={[0.184, 0.102, 0.158]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.006']} position={[0.56, 0.623, 0.706]} rotation={[-0.124, 0.209, 0.233]} scale={0.09} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cute_mug_-_free_3d_model.glb')
